-- 테이블 생성

-- 회원관리 
CREATE TABLE PROJECTUSER(
	ID VARCHAR2(100),
	PASSWORD VARCHAR2(200) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	ADDRESS VARCHAR2(200),
	PHONE VARCHAR2(20) NOT NULL,
	JOINDATE DATE,
	AUTH CHAR(1) DEFAULT 'U',
	ENABLED CHAR(1) DEFAULT 'Y'
);
ALTER TABLE PROJECTUSER ADD CONSTRAINT PROJECTUSER_PK PRIMARY KEY (ID);


--문의게시판
CREATE TABLE PROJECTBOARD(
	SEQ NUMBER,
	ID VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	REPLY CHAR(1) DEFAULT 'N',
	REGDATE DATE,
	DELFLAG CHAR(1) DEFAULT 'N'
);
ALTER TABLE PROJECTBOARD ADD CONSTRAINT PROJECTBOARD_PK PRIMARY KEY (SEQ);
ALTER TABLE PROJECTBOARD ADD CONSTRAINT PROJECTBOARD_FK FOREIGN KEY (ID) REFERENCES PROJECTUSER(ID);
CREATE SEQUENCE PROJECTBOARD_SEQ START WITH 20 INCREMENT BY 1 NOCACHE;


--파일업로드
CREATE TABLE PROJECTFILE(
	SEQ NUMBER,
	BOARDSEQ NUMBER NOT NULL,
	FILENAME VARCHAR2(100) NOT NULL,
	FILESIZE NUMBER,
	REGDATE DATE,
	ENABLED CHAR(1) DEFAULT 'Y'
);
ALTER TABLE PROJECTFILE ADD CONSTRAINT PROJECTFILE_PK PRIMARY KEY (SEQ);
CREATE SEQUENCE PROJECTFILE_SEQ START WITH 20 INCREMENT BY 1 NOCACHE;


--자유게시판
CREATE TABLE PROJECTFILEBOARD(
	SEQ NUMBER,
	ID VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	REGDATE DATE,
	DELFLAG CHAR(1) DEFAULT 'N'
);
ALTER TABLE PROJECTFILEBOARD ADD CONSTRAINT PROJECTFILEBOARD_PK PRIMARY KEY (SEQ);
ALTER TABLE PROJECTFILEBOARD ADD CONSTRAINT PROJECTFILEBOARD_FK FOREIGN KEY (ID) REFERENCES PROJECTUSER(ID);
CREATE SEQUENCE PROJECTFILEBOARD_SEQ START WITH 20 INCREMENT BY 1 NOCACHE;